# Generated by Django 4.2 on 2023-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('osm_id', models.CharField(blank=True, max_length=12, null=True)),
                ('code', models.SmallIntegerField(blank=True, null=True)),
                ('fclass', models.CharField(blank=True, max_length=28, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poi',
                'managed': False,
            },
        ),
    ]
